# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShowDoMilhao' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShowDoMilhao
	pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'ShowDoMilhaoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShowDoMilhaoUITests' do
    # Pods for testing
  end

end
